nodeApp:
  deployment:
    name: my-app
    replicas: 1
  selector:
    app: my-app
  container:
    name: my-app
    image: imzainazm/nodeapp
    port: 3000
  service:
    name: my-app
    type: NodePort
    ports:
      port: 3000
      targetPort: 3000
      nodePort: 30021


additionalEnv: []
  # additionalEnv:
  #   - name: SOME_ENV_VAR
  #     value: some_value
  #   - name: ANOTHER_ENV_VAR
  #     value: another_value
