apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodbService.name }}
spec:
  selector:
    app: {{ .Values.mongodbService.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodbService.ports.port }}
      targetPort: {{ .Values.mongodbService.ports.targetPort }}