apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
spec:
  rules:
  - host: www.dogimages.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 8081
      - path: /get-profile
        pathType: Prefix
        backend:
          service:
            name: my-app
            port:
              number: 3000
