apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dog-images-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/imzainhafeez/docker-project.git'
    targetRevision: feature/argoCD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true