apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secret.name }}
type: Opaque
data:
  {{ .Values.mongo.secret.data.mongoRootUsernameKey }}: {{ .Values.mongo.secret.data.mongoRootUsernameValue }}
  {{ .Values.mongo.secret.data.mongoRootPasswordKey }}: {{ .Values.mongo.secret.data.mongoRootPasswordValue }}
