apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
        {{- if .Values.additionalLabels }}
        {{- range $key, $value := .Values.additionalLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.adminUsername.secretName }}
              key: {{ .Values.adminUsername.key }}
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.adminPassword.secretName }}
              key: {{ .Values.adminPassword.key }}
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-express-config
              key: {{ .Values.configMap.key }}
        {{- if .Values.additionalEnv }}
        {{- range .Values.additionalEnv }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
        {{- end }}
