apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: {{ .Values.mongoexpress.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongoexpress.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongoexpress.appName }}
    spec:
      containers:
      - name: {{ .Values.mongoexpress.appName }}
        image: {{ .Values.mongoexpress.imageName }}:{{ .Values.mongoexpress.imageTag }}
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.mongoexpress.appName }}
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.service.nodePort }}
