apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeApp.service.name }}
spec:
  type: {{ .Values.nodeApp.service.type }}
  ports:
  - port: {{ .Values.nodeApp.service.ports.port }}
    targetPort: {{ .Values.nodeApp.service.ports.targetPort }}
    nodePort: {{ .Values.nodeApp.service.ports.nodePort }}
  selector:
    app: {{ .Values.nodeApp.selector.app }}
