apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: {{ .Values.nodeApp.namespace }}
spec:
  replicas: {{ .Values.nodeApp.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodeApp.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodeApp.selector.app }}
        {{- range $key, $value := .Values.nodeApp.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.nodeApp.container.name }}
        image: {{ .Values.nodeApp.container.image }}
        ports:
        - containerPort: {{ .Values.nodeApp.container.port }}
