---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    mongo-secret.yml: AgCaSm0O1hXeXXNvA0JRGbdTyWQzUC5VRUkCgsibc0D9kR2CjrTjF551XjhrgZH3NSXdahzNqh1scYEN2fxl9mpz+3Ni90clpf6DeiC8nyqxJQlkjjyBGYn96p+1ogrUuedUVRiuzq1immz4AHDGLpdY2rRMkWg2Nf0OrXWuDBeJXNVHiwk9hGCHQbdVqvEP4iFyqOBiXHc7DxxoVT+wmuRi7hx0MXxOll3oyEKtNMLBU07+ndTy5fwYsIOtFe6ALK2kELUGlSfJ4FB9JJhkya25hmdY/HTlsTDXhD/vgWPdWUqDEq4S5pV232NdGG06tuqv4TWPmMnF6kL4EzaP3Ke8r2QPsvwIsjlUz0ruMT3VJDJkLZlo3P30d005SbnEt6eJThxkbTvuGW38FjnQ6/g2X54bSfDM7I+dBZmt32H8hdCSVQZxtCeLBRNjnCPdxFaknY8DYh3Dn+EW4txBBGmIU9K70/6Ztk9OAJ7DR8ix3CYqnzbWP3hfOpGZWfKAKiK+vjfPiOnwNwA9e8ku+eVksm1GbHKM9U8vKmW/i1MvRKg/OC1k1+yqV5WOTFTBqI0ie3Va1OAb+LcTeNTOBH89IxNKFozqSL83E8RGyK4Nryqz27Mf0QH5I7PSjT75CYt0kabI/bqo/0IPdm/BlBu8AN9v2PmvthRUCi4e89jtireTapJGOjMcj4vZolQCcUAUa5rHyWkYUvnxsecbWW04Ukvu5Q0je4BWhUzzP2DXCFac/vppWTht8fjug1BBHnJ9mN3VapWqkl7zh3er41ONMUSXIAheKOUPKtrCT9ooybuVpzsnz96sl4QdlR7qdoQI8KxPTYmtFjQphFp5ZTiKvhcRTZMVfeXOEU/oYRaTMUngjvLazIU2whxA9UCWNEn5g5KoRbjMKQ==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
